apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-svc
spec:
  ports:
  - name: db-svc
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-deployment
    name: voting-app