apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
    name: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
      name: voting-app
  template:
    metadata:
      name: postgres-deployment
      labels:
        app: postgres-deployment
        name: voting-app
    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
        