apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-deployment
    name: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
      name: voting-app
  template:
    metadata:
      name: redis-deployment
      labels:
        app: redis-deployment
        name: voting-app
    spec:
      containers:
        - name: redis 
          image: redis
          ports:
            - containerPort: 6379
        