apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-deployment
      app: voting-app
  template:
    metadata:
      name: voting-app-deployment
      labels:
        name: voting-app-deployment
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: kennytoro/voting-app
          ports:
            - containerPort: 80
    