apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-deployment
      app: voting-app
  template:
    metadata:
      name: worker-app-deployment
      labels:
        name: worker-app-deployment
        app: voting-app
    spec:
      containers:
        - name: worker-app
          image: kennytoro/worker-app
          